### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [cuducos/airnope#1]
bruh i see code this is something good but i have a request add json or other code to deploy on heroku

**Comment by cuducos** [comment]
I haven't used Heroku for a long time. But as far as I remember, there is no need for JSON or any extra code. The `Dockerfile` in the root does it.

If not, please re-open this issue with what you have tried and the error logs so I can work on it.

**Comment by Ashrafmdmatin41** [comment]
ok i will add code
